### PR TITLE
Manual update deps and update codegen

### PR DESCRIPTION
**Pull request by lberk**
Needed after knative/eventing#3046 fix has landed

### CODE REVIEW

**Comment by lionelvillard** [comment]
@lberk this PR didn't pick up the latest eventing

**Comment by lionelvillard** [comment]
nvm. The revision is correct.

**Comment by lberk** [comment]
@lionelvillard same base reconciler issue, commit incoming shortly

**Comment by lberk** [comment]
/close
#1163 has the rbac fixes needed to fix the kafka/github tests

**Pull request closed without merging**
