### PR TITLE
Add ClusterRole to get, list and watch sources in eventing-contrib

### LINKED ISSUE #583: Add ClusterRole to get, list and watch "awssqssources", "camelsources", "kafkasources" and "githubsources"
## Expected Behavior
Add ClusterRole to get, list and watch "awssqssources", "camelsources", "kafkasources" and "githubsources"
## Actual Behavior
In PR knative/eventing#1849, we added ClusterRole to get, list and watch  "awssqssources", "camelsources", "kafkasources" and "githubsources" in config/200-source-resolvers-clusterrole.yaml.
This is a temporary solution. Such ClusterRole should eventually be moved to config directories in https://github.com/google/eventing-contrib.

## Steps to Reproduce the Problem

  1.
  2.
  3.

## Additional Info

### PR DESCRIPTION
**Pull request by capri-xiyue**
Fixes #583 

## Proposed Changes

  * Add ClusterRole to get, list and watch "awssqssources", "camelsources", "kafkasources" and "githubsources" 
  *
  *

**Release Note**

```release-note
```

### CODE REVIEW

**Comment by n3wscott** [comment]
/hold
until https://github.com/knative/eventing/pull/1856 lands

**Comment by n3wscott** [comment]
/lgtm
/approve
unhold when knative/eventing#1856 lands

**Comment by capri-xiyue** [comment]
I will create another issue to add cluster role to get,list and watch cunchbase /unhold

**Pull request merged**
