### PR TITLE
Update to sdk-go V2.0.0-RC1

### PR DESCRIPTION
**Pull request by slinkydeveloper**
Signed-off-by: Francesco Guardiani <francescoguard@gmail.com>

**Release Note**

```release-note
Update sdk-go to v2.0.0-RC1
```

### CODE REVIEW

**Comment by mattmoor** [comment]
Looks like you need to run update-codegen :(

**Comment by slinkydeveloper** [comment]
> Looks like you need to run update-codegen

I did it, but there is nothing new to commit!

**Pull request merged**
