### PR TITLE
Source Migration for kafkaSource, promSource and githubSource

### LINKED ISSUE #864: [PrometheusSource] Migrate to sources.knative.dev api group
## Expected Behavior
The resource is inside of the api group `sources.knative.dev`

## Actual Behavior
`sources.eventing.knative.dev`

/assign syedriko

### PR DESCRIPTION
**Pull request by lberk**
Fixes #864 
#863
#862

### CODE REVIEW

**Comment by matzew** [comment]
@lberk hrm... something wrong :-)

**Comment by lionelvillard** [comment]
/hold

this change is not backward compatible.

**Comment by lberk** [comment]
@lionelvillard While this isn't a backward compatible change, how would you suggest we approach the change?  double up the apigroups to have a `sources.eventing.knative.dev` in parallel to `eventing.knative.dev` for a release? (before dropping the former?)  I think @n3wscott changed eventing by moving apigroups to legacysources first (which in itself is a breaking change as well?)
@n3wscott @matzew thoughts?

**Comment by lberk** [comment]
As an aside, isn't this part of the rational for still being in `v1alpha1` ? that we can still make changes like this to the apigroup names?

**Comment by matzew** [comment]
> As an aside, isn't this part of the rational for still being in v1alpha1 ? that we can still make changes like this to the apigroup names?

yeh, I think so too

**Comment by n3wscott** [comment]
> I think @n3wscott changed eventing by moving apigroups to legacysources first (which in itself is a breaking change as well?)

It is code breaking, API non-breaking. So old releases still work with the API in the ApiServer.

**Comment by n3wscott** [comment]
My vote would be to allow in an API breaking change like this but I wanted to leave that choice to the owners of the sources. It is a ton of work to do what I had to do in eventing with the legacy client.

**Comment by matzew** [comment]
> My vote would be to allow in an API breaking change like this but I wanted to leave that choice to the owners of the sources. It is a ton of work to do what I had to do in eventing with the legacy client.

Honestly, I feel exactly the same, and I see why you did the extra mile for eventing CORE.   

for GH/Prom/KafkaSource, I'd be OK to let it break.   At some point users have to migrate anyways.

Just my $0.02

**Comment by Abd4llA** [comment]
I think at v1alpha1 unless we explicitly hear from owners or users of specific sources that they wanna avoid a breaking change, we should go ahead and do specially considering the overhead would be non beneficial.

**Comment by lionelvillard** [comment]
I'm also fine with breaking changes.

**Comment by lberk** [comment]
Thanks folks, if everybody's ok with the changes as is -- could I get a `/lgtm` ?

**Pull request merged**
