### PR TITLE
remove gitlab

### PR DESCRIPTION
**Pull request by lionelvillard**
## Proposed Changes

-
-
-

**Release Note**

```release-note
The GitLab source artifacts have moved to https://github.com/knative-sandbox/eventing-gitlab

```

**Docs**

/hold

@sebgoa 
@tzununbekov

### CODE REVIEW

**Comment by lionelvillard** [comment]
TestGrid is green: https://testgrid.knative.dev/eventing-gitlab#nightly
/unhold

**Comment by pierDipi** [comment]
Can you rebase?

**Pull request merged**
