### PR TITLE
[master] Auto-update dependencies

### PR DESCRIPTION
**Pull request by mattmoor**
Produced via:
  `./hack/update-deps.sh --upgrade && ./hack/update-codegen.sh`
/assign grantr lberk matzew n3wscott
/cc grantr lberk matzew n3wscott

### CODE REVIEW

**Comment by lberk** [comment]
Failure looks related to a change I made in pkg, taking a look now

**Comment by lberk** [comment]
Possible fix in #1559

**Comment by matzew** [comment]
/close

you can not write something after the prow command, @lberk  :smile_cat:

**Pull request closed without merging**
