### PR TITLE
remove camel from release

### PR DESCRIPTION
**Pull request by lionelvillard**
## Proposed Changes

-
-
-

**Release Note**

```release-note
The Camel artifacts have moved to https://github.com/knative-sandbox/eventing-camel
```

**Docs**

@vaikas @nicolaferraro

### CODE REVIEW

**Comment by aliok** [comment]
/hold

As per https://github.com/knative/eventing-contrib/pull/1573#issuecomment-692802453

**Comment by aliok** [comment]
@lionelvillard can you rebase?

**Comment by lionelvillard** [comment]
@aliok @lberk I rebased it.

**Pull request merged**
