### PR TITLE
remove couchdb

### PR DESCRIPTION
**Pull request by lionelvillard**
## Proposed Changes

-
-
-

**Release Note**

```release-note
The CouchDB source artifacts have moved to https://github.com/knative-sandbox/eventing-couchdb

```

**Docs**

/hold

### CODE REVIEW

**Comment by pierDipi** [comment]
Please, update release notes.

**Comment by lionelvillard** [comment]
@pierDipi done. thanks!

**Review by pierDipi — APPROVED** [review]
/lgtm
/hold

Do we need to wait for a successful nightly release? https://testgrid.knative.dev/eventing-couchdb#nightly&width=20

**Comment by lionelvillard** [comment]
nightly is green. https://testgrid.knative.dev/eventing-couchdb#nightly

/unhold

**Review by aliok — APPROVED** [review]
/lgtm
/approve

:fire:

**Comment by pierDipi** [comment]
```
/home/prow/go/src/knative.dev/eventing-contrib/hack/update-codegen.sh: line 143: syntax error near unexpected token `<<<'
```

**Comment by lionelvillard** [comment]
@aliok @pierDipi finally good to go!

**Pull request merged**
