### PR TITLE
Remove natss

### PR DESCRIPTION
**Pull request by matzew**
Drop the Natss channel, which has moved to https://github.com/knative-sandbox/eventing-natss 

**Release Note**
```release-note
The Natss artifacts have moved to https://github.com/knative-sandbox/eventing-natss
```

### CODE REVIEW

**Comment by aliok** [comment]
If you fix this pr, can you also add a release note in the PR description for the repo move, similar to the note in https://github.com/knative/eventing-contrib/pull/1586 ?

**Comment by lberk** [comment]
@matzew looks like a real failure with the test runner:
`error: the path "natss/config/broker/natss.yaml" does not exist`

**Review by aliok — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
