### PR TITLE
Updated eventing

### PR DESCRIPTION
**Pull request by slinkydeveloper**
Signed-off-by: Francesco Guardiani <francescoguard@gmail.com>

Updated eventing to reflect changes from https://github.com/knative/eventing/pull/3080

### CODE REVIEW

**Comment by matzew** [comment]
@slinkydeveloper  still something missing ?

**Comment by slinkydeveloper** [comment]
@matzew to me it looks like we have a conflict in dependency resolution https://prow.knative.dev/view/gcs/knative-prow/pr-logs/pull/knative_eventing-contrib/1192/pull-knative-eventing-contrib-build-tests/1257955543876636674#1:build-log.txt%3A1575

But i can't say where the conflict comes from, the go.mod forces a specific version of client go

```
k8s.io/client-go => k8s.io/client-go v0.16.4
```

**Comment by matzew** [comment]
/close 

see #1208

**Pull request closed without merging**
