### PR TITLE
CouchDB sink now uses Destination

### PR DESCRIPTION
**Pull request by lionelvillard**
## Proposed Changes

  * CouchDB sink is now a Destination

### CODE REVIEW

**Comment by matzew** [comment]
/hold

wait until this also has merged for CORE sources.

I guess that means we do this in 0.11 ?

**Comment by grantr** [comment]
@matzew this change has already merged for core sources right?

**Comment by matzew** [comment]
/hold cancel 

core was already merged - sorry! 
just unfortunate timing, so close to the release .... bad coordination, IMO ...

**Comment by matzew** [comment]
> feels like it was just quickly pushed through ... disappointed

not this one, more on the _eventing core_ ....

**Comment by lionelvillard** [comment]
/hold cancel

Added CRD changes

**Pull request merged**
