### PR TITLE
Drop reconciler.Base from eventing.

### PR DESCRIPTION
**Pull request by n3wscott**
Dependent on https://github.com/knative/eventing/pull/2943

## Proposed Changes

- Remove last pointer to reconciler.Base from eventing.

**Release Note**

```release-note
NONE
```

### CODE REVIEW

**Comment by n3wscott** [comment]
/hold 
until the upstream PR lands

**Comment by n3wscott** [comment]
There is no dep on knative/eventing#2943

/unhold

**Comment by matzew** [comment]
@n3wscott mind doing a rebase? 

happy to /lgtm afterwards!

**Pull request merged**
