### PR TITLE
Adding default kubebuilder test and integrating it with controller sdk

### PR DESCRIPTION
**Pull request by n3wscott**
## Proposed Changes

  * Add the basic kubebuilder controller reconciler test and integrate it with the sdk. 
  * Attempting to better test the skd.

**Release Note**
```release-note
NONE.
```

### CODE REVIEW

**Comment by n3wscott** [comment]
This is a followup to https://github.com/knative/eventing-sources/pull/77

**Comment by n3wscott** [comment]
/hold
```
I1107 15:31:02.900] 2018/11/07 15:31:02 fork/exec /usr/local/kubebuilder/bin/etcd: no such file or directory
I1107 15:31:02.900] FAIL	github.com/knative/eventing-sources/pkg/controller/sdk	0.537s```

The issue is kubebuilder testing framework assumes the etcd binary is installed locally by default.

**Comment by matzew** [comment]
@n3wscott still relevant?!

**Pull request closed without merging**
