### PR TITLE
WIP: Kafka e2e

### PR DESCRIPTION
**Pull request by matzew**
just starting the work

### CODE REVIEW

**Comment by aslom** [comment]
any idea why e2e tests failed - run again?

**Comment by aslom** [comment]
A nit strange that some tests fail 0 seconds and 2 fail with timeouts?

```

channel_single_event_helper.go:58: Failed to get all test resources ready: failed waiting for {TypeMeta:{Kind:Subscription APIVersion:messaging.knative.dev/v1alpha1} ObjectMeta:{Name:e2e-singleevent-subscription-structured GenerateName: Namespace:test-single-structured-event-for-channel-kafka-channel-747j5 SelfLink: UID: ResourceVersion: Generation:0 CreationTimestamp:0001-01-01 00:00:00 +0000 UTC DeletionTimestamp:<nil> 

channel_single_event_helper.go:58: Failed to get all test resources ready: failed waiting for {TypeMeta:{Kind:Subscription APIVersion:messaging.knative.dev/v1alpha1} ObjectMeta:{Name:e2e-singleevent-subscription-binary GenerateName: Namespace:test-single-binary-event-for-channel-kafka-channel-wvfjz SelfLink: UID: ResourceVersion: Generation:0 CreationTimestamp:0001-01-01 00:00:00 +0000 UTC DeletionTimestamp:<nil> DeletionGracePeriodSeconds:<nil> Labels:map[] Annotations:map[] OwnerReferences:[] Initializers:nil Finalizers:[] ClusterName: ManagedFields:[]}} to become ready: timed out waiting for the condition
tracker.go:124: Cleaning resource: "e2e-singleevent-subscription-binary"

```

**Comment by chizhg** [comment]
@matzew can you revisit this PR when you get some time? It should help prevent issues like https://github.com/knative/eventing-contrib/issues/702

**Pull request closed without merging**
