### PR TITLE
GitHub destination & Updated clientSet rewrite

### LINKED ISSUE #693: Github Source usage of Desitination
The Github Source should adpot `Destination` type, https://docs.google.com/document/d/1EAf9NLwDX3c9DS8lr6KxjtgRXUmkFGIcG6DeAYd5UHI/edit#

### PR DESCRIPTION
**Pull request by lberk**
Fixes #693

## Proposed Changes

  * Update the underlying reconciler to use `knative.dev/pkg`
  * Update Sink to use Destination
  * Update githubsource types accordingly

**Release Note**
None
```release-note
```

### CODE REVIEW

**Comment by lberk** [comment]
/wip
still figuring out finalizer issue with deleting the webhook

**Comment by matzew** [comment]
I think we need to update the 300-xxx file too, @lberk 

see here: 
https://github.com/knative/eventing-contrib/pull/711/files#diff-a47097a093a3ef0fb5f8661d11edbfebR77-R105

**Comment by matzew** [comment]
(Including my comment w/ a link to a different PR)

**Comment by lberk** [comment]
/hold cancel
(ready for review)

**Pull request merged**
