### PR TITLE
Update go.mod to specify the module is go1.14

### PR DESCRIPTION
**Pull request by dprotaso**
Thus the go commands will default to `-mod=vendor`

See: https://golang.org/doc/go1.14#go-command

### CODE REVIEW

**Comment by matzew** [comment]
@dprotaso  hey Dave, mind to rebase the PR ? 

/approve

**Comment by dprotaso** [comment]
@matzew done

**Comment by matzew** [comment]
@dprotaso I am sorry, something is messing w/ the darn `verndor/modules.txt` ...

:-(

**Comment by dprotaso** [comment]
looks like a legit data race 

```
WARNING: DATA RACE
Read at 0x00c000414163 by goroutine 33:
  testing.(*common).logDepth()
      /root/.gvm/gos/go1.14.2/src/testing/testing.go:669 +0xa1
  testing.(*common).log()
      /root/.gvm/gos/go1.14.2/src/testing/testing.go:662 +0x8f
  testing.(*common).Logf()
      /root/.gvm/gos/go1.14.2/src/testing/testing.go:701 +0x21
  knative.dev/eventing-contrib/gitlab/pkg/adapter.TestGracefulShutdown.func1()
      /home/prow/go/src/knative.dev/eventing-contrib/gitlab/pkg/adapter/receive_adapter_test.go:162 +0x64
Previous write at 0x00c000414163 by goroutine 32:
  testing.tRunner.func1()
      /root/.gvm/gos/go1.14.2/src/testing/testing.go:977 +0x467
  testing.tRunner()
      /root/.gvm/gos/go1.14.2/src/testing/testing.go:995 +0x20d
Goroutine 33 (running) created at:
  knative.dev/eventing-contrib/gitlab/pkg/adapter.TestGracefulShutdown()
      /home/prow/go/src/knative.dev/eventing-contrib/gitlab/pkg/adapter/receive_adapter_test.go:161 +0x18d
  testing.tRunner()
      /root/.gvm/gos/go1.14.2/src/testing/testing.go:991 +0x1eb
Goroutine 32 (running) created at:
  testing.(*T).Run()
      /root/.gvm/gos/go1.14.2/src/testing/testing.go:1042 +0x660
  testing.runTests.func1()
      /root/.gvm/gos/go1.14.2/src/testing/testing.go:1284 +0xa6
  testing.tRunner()
      /root/.gvm/gos/go1.14.2/src/testing/testing.go:991 +0x1eb
  testing.runTests()
      /root/.gvm/gos/go1.14.2/src/testing/testing.go:1282 +0x527
  testing.(*M).Run()
      /root/.gvm/gos/go1.14.2/src/testing/testing.go:1199 +0x2ff
  main.main()
      _testmain.go:46 +0x223
```

**Comment by dprotaso** [comment]
is that a known flake?

**Pull request merged**
