### PR TITLE
Allowing sinkbinding for websocket source

### PR DESCRIPTION
**Pull request by matzew**
Fixes #

## Proposed Changes

  * with the new `K_SINK` and `Sinkbinding`, making the WebSocket Source ready for that

### CODE REVIEW

**Comment by matzew** [comment]
/assign @mattmoor 
/assign @n3wscott 

any thoughts?

**Comment by grantr** [comment]
Release notes followup: This looks like a new feature, but it didn't have a release note blurb :smiley:

**Pull request merged**
