### PR TITLE
Backport usage of Destination in CamelSource (#700) to release-0.10 b…

### LINKED ISSUE #694: Camel Source usage of Desitination
The Camel Source should adpot `Destination` type, https://docs.google.com/document/d/1EAf9NLwDX3c9DS8lr6KxjtgRXUmkFGIcG6DeAYd5UHI/edit#

### PR DESCRIPTION
**Pull request by nicolaferraro**
…ranch

Fixes #694 on 0.10.x

## Proposed Changes

  * Same as #700

**Release Note**

```release-note
```

### CODE REVIEW

**Comment by nicolaferraro** [comment]
no way today..

**Comment by chizhg** [comment]
There is some change for the tests in the release-0.10 branch, please update your local release-0.10 and merge into this PR.

**Comment by nicolaferraro** [comment]
Thanks @chizhg, lionelvillard. It is be passing tests now.

**Pull request merged**
