### PR TITLE
Update Kafka loadgen for new loadgen interface

### PR DESCRIPTION
**Pull request by ericlem**
Fixes #2208

## Proposed Changes
Updates kafka loadgen to use new fixedBody parameter from eventing loadgen.

This needs to be updated in concert with:
 https://github.com/knative/eventing/pull/2415

This First commit will be removed and replaced with an appropriate master pull before pushing (and after pushing to Eventing)

**Release Note**

NONE

### CODE REVIEW

**Comment by slinkydeveloper** [comment]
https://github.com/knative/eventing/pull/2415 merged, can you update this one?

**Comment by ericlem** [comment]
Waiting for #839
Need changes from that for the pull from eventing to succeed.

**Comment by ericlem** [comment]
#839 merged, so pulled in dependencies and unblocked.

**Pull request merged**
