### PR TITLE
Pressure wash kafka code.

### PR DESCRIPTION
**Pull request by markusthoemmes**
## Proposed Changes

Gave the kafka code a good scrub!

- Removed unused code.
- Removed unnecessary conversion.
- Shortened expressions (bool comparisons, channel reads)
- Removed deprecated code.

### CODE REVIEW

**Comment by slinkydeveloper** [comment]
I think go coverage doesn't like that you removed code from kafka/client.go :)

**Comment by markusthoemmes** [comment]
/hold

Gonna add test cleanups too. They are all kafka related.

**Comment by markusthoemmes** [comment]
/hold cancel

Ready for another look.

**Comment by duglin** [comment]
“Pressure wash” LOL

**Comment by slinkydeveloper** [comment]
For go-coverage, i think you can make it happy just creating failing tests for the `New*` functions

**Comment by matzew** [comment]
the client is below 50% that why it fails - but, heck it was below that number before as well ...

**Pull request merged**
