### PR TITLE
Auto-update dependencies

### PR DESCRIPTION
**Pull request by mattmoor**
Produced via:
  `dep ensure -update knative.dev/test-infra knative.dev/pkg knative.dev/serving knative.dev/eventing`
/assign n3wscott

### CODE REVIEW

**Comment by n3wscott** [comment]
poor poor eventing contrib. You don't deserve this...

**Comment by grantr** [comment]
Do we need this for 0.11 cut or can it wait?

**Comment by mattmoor** [comment]
If this is needed, then someone should work on manually fixing things.

**Comment by grantr** [comment]
I think this breakage was caused by https://github.com/knative/eventing/pull/2256 and https://github.com/knative/eventing/pull/2232. Since it's an internal type change that isn't externally visible, we can cut 0.11 without merging it.

**Pull request closed without merging**
