### PR TITLE
Migrate to knative.dev/eventing-contrib 🏃‍♀️

### PR DESCRIPTION
**Pull request by n3wscott**
## Proposed Changes

- Move import paths of `github.com/knative/eventing-contrib` to become `knative.dev/eventing-contrib`
- Move import paths of `github.com/knative/eventing` to become `knative.dev/eventing`

**Release Note**

```release-note
Developers will need to move github.com/knative/eventing-contrib to knative.dev/eventing-contrib in their $GOPATH.
```

Depends on https://github.com/knative/eventing/pull/1655

### CODE REVIEW

**Comment by n3wscott** [comment]
/hold 

until https://github.com/knative/eventing/pull/1655 merges.

**Comment by chaodaiG** [comment]
/hold
until https://github.com/knative/test-infra/pull/1238 merges

**Pull request merged**
