### PR TITLE
Updating pkg to latest for 0.9 release.

### PR DESCRIPTION
**Pull request by n3wscott**
## Proposed Changes

- Prepping for 0.9 release. Update knative.dev/pkg to latest from branch release-0.9.

**Release Note**

```release-note
NONE
```

/cc @mattmoor

### CODE REVIEW

**Comment by sayanh** [comment]
We would need this fix https://github.com/knative/eventing-contrib/commit/200324fba6b8571a3a193da042c9de24e1fc5db2

**Comment by n3wscott** [comment]
/retest

works locally... not sure what's up.

**Comment by n3wscott** [comment]
ah! eventing is out of date.

**Pull request merged**
