### PR TITLE
Upgrade CamelSources to Camel K 1.1.0

### PR DESCRIPTION
**Pull request by nicolaferraro**
## Proposed Changes

- Upgrade CamelSource to latest version of Camel K (1.1.0)

**Release Note**

```release-note

```

**Docs**

### CODE REVIEW

**Comment by pierDipi** [comment]
There is this issue open: https://github.com/knative/eventing-contrib/issues/1414, so there are no tests for Camel running.

**Comment by nicolaferraro** [comment]
> There is this issue open: #1414, so there are no tests for Camel running.

Thanks, I will look into that

**Review by matzew — APPROVED** [review]
/lgtm
/approve

**Comment by pierDipi** [comment]
Flaky https://github.com/knative/eventing-contrib/issues/1433
/retest

**Pull request merged**
