### PR TITLE
Add Ready column to GithubSource

### PR DESCRIPTION
**Pull request by mattmoor**

### CODE REVIEW

**Comment by mattmoor** [comment]
/retest

cc @chaodaiG

**Comment by matzew** [comment]
@mattmoor @Harwayne @grantr  IMO its a huge problem that almost every CI run has memory issues :-( 

@chizhg mentioned that for serving some resource improvements where done ?! to have better machine ?

**Comment by chizhg** [comment]
> @mattmoor @Harwayne @grantr IMO its a huge problem that almost every CI run has memory issues :-(
> 
> @chizhg mentioned that for serving some resource improvements where done ?! to have better machine ?

I have already increased the resource requests for the build test jobs. Hopefully the issue can go away :)

**Pull request merged**
