### PR TITLE
Add missing flow field to Camel source CRD validation

### LINKED ISSUE #566: Missing flow field from Camel source CRD validation
## Expected Behavior

It is possible to create a Camel source with a `flow` field to inline a route.

Knative contrib 0.8.x.

## Actual Behavior

```      
error: error validating "source_timer_flow.yaml": error validating data: ValidationError(CamelSource.spec.source): unknown field "flow" in dev.knative.eventing.sources.v1alpha1.CamelSource.spec.source
```

## Steps to Reproduce the Problem

```
$ kubectl apply -f source_timer_flow.yaml                 
error: error validating "source_timer_flow.yaml": error validating data: ValidationError(CamelSource.spec.source): unknown field "flow" in dev.knative.eventing.sources.v1alpha1.CamelSource.spec.source; if you choose to ignore these errors, turn validation off with --validate=false
```

### PR DESCRIPTION
**Pull request by astefanutti**
Fixes #566

## Proposed Changes

Add the `flow` field to the Camel source CRD validation section.

/cc @nicolaferraro

### CODE REVIEW

**Comment by astefanutti** [comment]
@googlebot I signed it!

**Comment by n3wscott** [comment]
/ok-to-test
/approve

Someone who works with Camel should lgtm, thanks!

**Comment by nicolaferraro** [comment]
LGTM

**Comment by n3wscott** [comment]
/lgtm

Thanks @nicolaferraro

**Pull request merged**
