### PR TITLE
[RELEASE 0.13] Backport a minimal fix for GitHubSource

### PR DESCRIPTION
**Pull request by mattmoor**
See #997, #1007, #1009 for additional context.

/assign @lionelvillard

### CODE REVIEW

**Comment by lionelvillard** [comment]
it's failing because the container images haven't been built (by ko I assume):

```
 image: knative.dev/eventing/cmd/channel_broker
```

Could it be the latest ko does not support non-ko URL (`ko:...`) ?

**Comment by mattmoor** [comment]
@lionelvillard Good catch.  No, `ko` needs to support paths without the scheme, but it's likely it ignored these with `--strict`.  @chaodaiG is `./hack/release.sh` being run from HEAD...?

**Comment by mattmoor** [comment]
🤔 Did the other PR not merge yet?

**Comment by mattmoor** [comment]
It merged, but this is also a different code path that seems to be pulling from HEAD 🤦‍♂

**Pull request merged**
