### PR TITLE
[release-0.17] Auto-update dependencies

### PR DESCRIPTION
**Pull request by mattmoor**
Produced via:
  `./hack/update-deps.sh --upgrade && ./hack/update-codegen.sh`
/assign grantr lberk matzew n3wscott
/cc grantr lberk matzew n3wscott

### CODE REVIEW

**Review by aliok — APPROVED** [review]
/lgtm
/approve

**Comment by aliok** [comment]
/retest

Flaky TestBrokerRedelivery ...

**Comment by pierDipi** [comment]
@aliok https://github.com/knative/eventing/pull/3968 should fix it

**Comment by aliok** [comment]
/retest

Still TestBrokerRedelivery

**Pull request merged**
