### PR TITLE
Bump to K8s 18.8

### PR DESCRIPTION
**Pull request by vaikas**
As part of the work to upgrade to k8s 18.8, this is work in progress to update our deps to that and the fixes for resulting fallout.

## Proposed Changes

- Update k8s* to 18.8
- For the Camel source, continue work in: https://github.com/knative-sandbox/eventing-camel
- I copied this repo there as a starting point.
- Remove camel from this repo.

**Release Note**

```release-note
- 🧽 Update or clean up current behavior

Uses k8s 18.8 APIs. No new features from them are being used however, just the client code.

- 🗑️ Remove feature or internal logic

Remove camel source from this repo. move it to https://github.com/knative-sandbox/eventing-camel
```

**Docs**

### CODE REVIEW

**Comment by vaikas** [comment]
Since there's a dependency on the camel-k here, perhaps we should use this opportunity and move it to knative-sandbox before this migration so we can unblock the others?

**Comment by nicolaferraro** [comment]
> Since there's a dependency on the camel-k here, perhaps we should use this opportunity and move it to knative-sandbox before this migration so we can unblock the others?
> @nicolaferraro is this something that makes sense to you? And apologies if you're not the right person, did some rudimentary digging and seemed up your alley :)

It makes sense @vaikas. I see the eventing-camel repo is already there. Do you want me to take this task?

**Comment by vaikas** [comment]
@nicolaferraro Yes please :)

**Comment by vaikas** [comment]
@nicolaferraro I pushed the repo to eventing camel. Just cloned the repo there and I'll move all the other bits.

**Pull request merged**
