### PR TITLE
Fix CI flow for eventing-contrib release branches

### PR DESCRIPTION
**Pull request by chizhg**
## Proposed Changes
* eventing-contrib release CI jobs are consistently failing - https://testgrid.knative.dev/knative-0.10#eventing-contrib, since it misses the required test images. 
Vendor the images from eventing, and upload them before test execution, if the job is running on a release branch.
* Clean up some **required** dependencies since they are not being used.

NOTE this PR does not fix the existing releases, but the future release cuts.

**Release Note**

```release-note
NONE
```

/cc @nachocano 
/cc @matzew

### CODE REVIEW

**Comment by matzew** [comment]
@chizhg mind rebasing this ?

**Comment by chizhg** [comment]
> @chizhg mind rebasing this ?

Done.

**Pull request merged**
