### PR TITLE
CamelSource e2e test (2nd attempt)

### LINKED ISSUE #271: e2e test for camel-k source
## Expected Behavior

have a e2e test for the camel-k source

## Actual Behavior

no test for this

### PR DESCRIPTION
**Pull request by nicolaferraro**
Fixes #271
Replaces #812 (if it works, cc: @maschmid)

## Proposed Changes

  * Add e2e tests for CamelSource

**Release Note**

```release-note
```

### CODE REVIEW

**Comment by maschmid** [comment]
@googlebot I consent.

**Comment by maschmid** [comment]
test/base has been moved to test/lib in eventing master https://github.com/knative/eventing/commit/300c8881ae86e11335404eaca8e98f82295db4d0

**Comment by nicolaferraro** [comment]
It's passing now!

**Pull request merged**
