### PR TITLE
verify codegen also check Gopkg.lock

### PR DESCRIPTION
**Pull request by chaodaiG**
Fixes https://github.com/knative/test-infra/issues/1213

### CODE REVIEW

**Comment by chaodaiG** [comment]
I don't see any reason why not, this file is always copy pasted among repos afaik

**Comment by grantr** [comment]
If it's not too much trouble, can you update this PR with the copy from eventing? That way they'll at least be identical from here forward. :smiley_cat:

**Comment by chaodaiG** [comment]
done :)

**Pull request merged**
