### PR TITLE
Pressure wash couchdb, ceph, gitlab and prometheus.

### PR DESCRIPTION
**Pull request by markusthoemmes**
## Proposed Changes

It seemed silly to create a PR for each of those as their fixes are so small'ish. Didn't want to create more noise here than necessary. Removes unused code mostly.

### CODE REVIEW

**Comment by sebgoa** [comment]
@tzununbekov

**Comment by slinkydeveloper** [comment]
@markusthoemmes can you try to rebase on master?

**Comment by markusthoemmes** [comment]
Yeah there's an actual build error in there too.

**Pull request merged**
