### PR TITLE
Remove kafka statefulset

### LINKED ISSUE #896: Remove KafkaSource Statefulset
The KafkaSource comes with a `Statefulset`, but in theory a `Deployment` should be good enough.  

We had done similar updates for the channel in the past.

### PR DESCRIPTION
**Pull request by matzew**
Fixes #896

## Proposed Changes

  * replace stateful set w/ Deployment for the controller of the kafka source
  * and add one statefulset for backward compatibility with 0 replicas

**Release Note**

```release-note
KafkaSource controller is now a Deployment. The statefulset is scaled down to 0 replicas
```

/assign @n3wscott 
/assign @lionelvillard

### CODE REVIEW

**Comment by matzew** [comment]
statefulset got scaled down:

```
NAME                       READY   AGE
kafka-controller-manager   0/0     16m
```

and we have a new depolyment (`k get deployments -nknative-eventing`):

```
NAME                       READY   UP-TO-DATE   AVAILABLE   AGE
eventing-controller        1/1     1            1           17m
eventing-webhook           1/1     1            1           17m
imc-controller             1/1     1            1           17m
imc-dispatcher             1/1     1            1           17m
kafka-controller-manager   1/1     1            1           13m
sources-controller         1/1     1            1           17m
```

Source works fine:

```
apiVersion: sources.knative.dev/v1alpha1
kind: KafkaSource
metadata:
  name: kafka-source
spec:
  consumerGroup: everythingisawesome
  bootstrapServers: my-cluster-kafka-bootstrap.kafka:9092
  topics: my-topic
  sink:
    apiVersion: serving.knative.dev/v1
    kind: Service
    name: event-display
```

**Comment by matzew** [comment]
Steps to reproduce:

1) installed KafkaSource 0.12.3 patch release
2) `ko apply` of my branch

**Comment by matzew** [comment]
FLAKE 

```
FAIL: TestBrokerChannelFlow (2.09s)
    --- FAIL: TestBrokerChannelFlow/TestBrokerChannelFlow-{NatssChannel_messaging.knative.dev/v1alpha1} (266.51s)
        test_runner.go:95: namespace is : "v1alpha1-5fkt8"
        creation.go:359: Creating service account &ServiceAccount{ObjectMeta:{eventing-broker-ingress  v1alpha1-5fkt8    0 0001-01-01 00:00:00 +0000 UTC <nil> <nil> map[] map[] [] []  []},Secrets:[]ObjectReference{},ImagePullSecrets:[]LocalObjectReference{},AutomountServiceAccountToken:n
```

**Comment by matzew** [comment]
/retest

TAKE IT !!

**Comment by lionelvillard** [comment]
Can you open an issue for removing the statefulset in 0.14?

**Comment by lionelvillard** [comment]
/lgtm
/hold

remove hold when issue is opened

**Comment by matzew** [comment]
https://github.com/knative/eventing-contrib/issues/935

/unhold

**Pull request merged**
