### PR TITLE
[master] Auto-update dependencies

### PR DESCRIPTION
**Pull request by mattmoor**
Produced via:
  `./hack/update-deps.sh --upgrade && ./hack/update-codegen.sh`
/assign grantr lberk n3wscott
/cc grantr lberk n3wscott

### CODE REVIEW

**Comment by lberk** [comment]
oops
/lgtm cancel

**Comment by mattmoor** [comment]
@n3wscott did something break upstream?

**Comment by n3wscott** [comment]
@mattmoor yes... working on it

**Comment by slinkydeveloper** [comment]
@n3wscott i already have the pr to fix it here https://github.com/knative/eventing-contrib/pull/1082

**Pull request closed without merging**
