### PR TITLE
remove github

### PR DESCRIPTION
**Pull request by lionelvillard**
## Proposed Changes

- remove github. 
-
-

**Release Note**

```release-note
The GitHub artifacts have moved to https://github.com/knative-sandbox/eventing-github
```

**Docs**

### CODE REVIEW

**Comment by lberk** [comment]
/hold -- until we verify the nightlies in sandbox are released properly (as discussed in sources wg)
@lionelvillard

**Comment by lionelvillard** [comment]
nightly build is green: https://testgrid.knative.dev/eventing-github#nightly

/unhold

**Pull request merged**
