### PR TITLE
Assorted linting fixes.

### PR DESCRIPTION
**Pull request by markusthoemmes**
## Proposed Changes

- Removed unused code.
- Remove unnecessary conversions.
- Replace deprecated code with new versions.
- Don't call `t.Fatal` in a separate goroutine.

/assign @slinkydeveloper @antoineco

### CODE REVIEW

**Comment by antoineco** [comment]
/lgtm
We should consider streamlining the use of `golangci-lint` in this project :)

**Comment by slinkydeveloper** [comment]
the broken tests doesn't seem a problem of this pr :smile:

**Comment by lionelvillard** [comment]
The github fixes are already in https://github.com/knative/eventing-contrib/pull/1297

**Pull request merged**
