### PR TITLE
Update knative.dev/eventing.

### PR DESCRIPTION
**Pull request by Harwayne**
Cherry-pick #724.

## Proposed Changes

  * Update knative.dev/eventing.
  * Update the tests to match the breaking change from knative/eventing#2181.

**Release Note**

```release-note
NONE
```

### CODE REVIEW

**Comment by Harwayne** [comment]
/test pull-knative-eventing-contrib-integration-tests

Boskos failure.

**Comment by Harwayne** [comment]
Sam error as two runs ago, Pods don't become ready:

`"message": "Back-off pulling image \"gcr.io/knative-boskos-14/keventing-contrib-e2e-img/6832/transformevents:latest\"",`

**Comment by adrcunha** [comment]
The problem is here:

```
>> Publishing test images
/home/prow/go/src/knative.dev/eventing-contrib /home/prow/go/src/knative.dev/eventing-contrib
/home/prow/go/src/knative.dev/eventing-contrib/test/e2e-tests.sh: line 104: cd: /home/prow/go/src/knative.dev/eventing: No such file or directory
find: './test/test_images': No such file or directory
/home/prow/go/src/knative.dev/eventing-contrib
```

This failure should fail the test, but it doesn't, thus you get confusing logs later.

**Comment by Harwayne** [comment]
Looks like #704 is the fix I want. Created #732 to cherry pick it into release-0.10.

**Pull request merged**
