### PR TITLE
use knative/pkg utils

### PR DESCRIPTION
**Pull request by runzexia**
Signed-off-by: runzexia <root@junwuhui.cn>

Fixes https://github.com/knative/eventing/issues/2842

## Proposed Changes

-
-
-

**Release Note**

```release-note

```

**Docs**

### CODE REVIEW

**Review by n3wscott — COMMENTED** [review]
/lgtm
/approve

**Comment by matzew** [comment]
@runzexia  can you please send the PR against:

https://github.com/knative-sandbox/eventing-kafka

?

that's the new location of the repo

**Comment by runzexia** [comment]
@matzew I created a new PR

**Pull request closed without merging**
