### PR TITLE
Fixed Kafka disconnection issue

### LINKED ISSUE #999: kafkasource receive-adapter stops partition consumer after a few minutes
**Describe the bug**
I created a KafkaSource object, consuming a Kafka topic and forwarding it (sink) to a KNative Service. It works well at first, consuming topic and passing the message to the Service. But after some time, without any new message to the topic, so being supposedly "idle", I get this in the logs:
```
{"level":"error","ts":"2020-03-06T22:32:00.659Z","logger":"kafkasource","caller":"adapter/adapter.go:153","msg":"An error has occurred while consuming messages occurred: ","stacktrace":"knative.dev/eventing-contrib/kafka/source/pkg/adapter.(*Adapter).Start.func3\n\tknative.dev/eventing-contrib/kafka/source/pkg/adapter/adapter.go:153"}
{"level":"info","ts":"2020-03-06T22:32:00.796Z","logger":"kafkasource","caller":"kafka/consumer_handler.go:90","msg":"Stopping partition consumer, topic: odfi, partition: 7"}
{"level":"info","ts":"2020-03-06T22:32:00.796Z","logger":"kafkasource","caller":"kafka/consumer_handler.go:90","msg":"Stopping partition consumer, topic: odfi, partition: 8"}
{"level":"info","ts":"2020-03-06T22:32:00.796Z","logger":"kafkasource","caller":"kafka/consumer_handler.go:90","msg":"Stopping partition consumer, topic: odfi, partition: 9"}
{"level":"info","ts":"2020-03-06T22:32:00.796Z","logger":"kafkasource","caller":"kafka/consumer_handler.go:90","msg":"Stopping partition consumer, topic: odfi, partition: 1"}
{"level":"info","ts":"2020-03-06T22:32:00.796Z","logger":"kafkasource","caller":"kafka/consumer_handler.go:90","msg":"Stopping partition consumer, topic: odfi, partition: 2"}
{"level":"info","ts":"2020-03-06T22:32:00.796Z","logger":"kafkasource","caller":"kafka/consumer_handler.go:90","msg":"Stopping partition consumer, topic: odfi, partition: 6"}
{"level":"info","ts":"2020-03-06T22:32:00.796Z","logger":"kafkasource","caller":"kafka/consumer_handler.go:90","msg":"Stopping partition consumer, topic: odfi, partition: 3"}
{"level":"info","ts":"2020-03-06T22:32:00.796Z","logger":"kafkasource","caller":"kafka/consumer_handler.go:90","msg":"Stopping partition consumer, topic: odfi, partition: 5"}
{"level":"info","ts":"2020-03-06T22:32:00.796Z","logger":"kafkasource","caller":"kafka/consumer_handler.go:90","msg":"Stopping partition consumer, topic: odfi, partition: 4"}
{"level":"info","ts":"2020-03-06T22:32:00.796Z","logger":"kafkasource","caller":"kafka/consumer_handler.go:90","msg":"Stopping partition consumer, topic: odfi, partition: 0"}
```
So there seem to be some error, but no detail. It says "while consuming messages" but I guess it's a generic message as there are no new messages incoming.

 **Expected behavior**
The receiver-adapter should not stop the consumers and continue to receive messages.

 **To Reproduce**
KafkaSource definition:
```
apiVersion: sources.knative.dev/v1alpha1
kind: KafkaSource
metadata:
  name: odfi-split
  namespace: ach
spec:
  consumerGroup: odfi-split
  bootstrapServers: my-cluster-kafka-bootstrap.kafka:9092
  topics: merchant-upload
  sink:
    apiVersion: serving.knative.dev/v1alpha1
    kind: Service
    name: odfi-split
```

 **Knative release version**
v0.13

 **Additional context**
OCP 4.3.1, AMQStreams Operator 1.3.0, OpenShift Serverless Operator 1.4.1, KNative Eventing Operator 0.12.0, KNative Kafka Operator 0.12.1

### PR DESCRIPTION
**Pull request by slinkydeveloper**
Signed-off-by: Francesco Guardiani <francescoguard@gmail.com>

Fixes #999

## Proposed Changes

- Wrapped `Consume` method invocation in a loop, like explained in the example here: https://godoc.org/github.com/Shopify/sarama#ConsumerGroup

### CODE REVIEW

**Comment by lberk** [comment]
@slinkydeveloper looks like this change (as-is) causes a data race?

**Comment by slinkydeveloper** [comment]
> @slinkydeveloper looks like this change (as-is) causes a data race?

Yep i'm investigating, doesn't seem a funny one

**Comment by guimou** [comment]
Thanks a lot guys! That will really help as otherwise the solution was not reliable enough to work with. :-)

**Pull request merged**
